title: Resume
logo: /assets/img/logo.png
description: Alberto's resume.
show_downloads: true
google_analytics:
name: Alberto Elias
current_title: Senior Software Engineer
phone_number:
email_address: hi@albertoelias.me
personal_website: albertoelias.me
github_url: github.com/albertoelias
collections_dir: resume_content
collections:
  - experience
  - publications
  - projects
  - skills
  - about
