title: Html resme
logo: /assets/img/logo.png
description: Christine's HTML resume.
show_downloads: true
google_analytics:
name: Christine Betts
current_title: Software Engineer
phone_number: (913) 909-2180
email_address: me@christinebetts.com
personal_website: christinebetts.com
github_url: github.com/chrstnb

collections_dir: resume_content

collections:
  - experience
  - publications
  - awards
  - education
  - volunteer_work
  - skills
